package org.uva.sea.ql.ast;

public enum ASTID {
	INTEGERLITERAL, STRINGLITERAL, BOOLEANLITERAL, 
	ADD, MIN, MUL, DIV, 
	POS, NEG, 
	EQ, NEQ, GT, LT, GET, LET,
	AND, OR,
	IFSTATEMENT, ELSESTATEMENT, BLOCK, QUESTION 
	
}
