form taxOfficeExample { 
  "Did you sell a house in 2010?" hasSoldHouse: boolean
  "Did you buy a house in 2010?" hasBoughtHouse: boolean
  "Did you enter a loan?" hasMaintLoan: boolean

  
if (hasBoughtHouse) {
    "What was the selling price?" sellingPrice: money
    "What was the buying price?" buyingPrice: money privateDebt + valueResidue
    "Private debts for the sold house:" privateDebt: integer
    "Value residue:" valueResidue: money sellingPrice + publicDebt
    "Public debts for the sold house:" publicDebt: money privateDebt + buyingPrice
  }
}