platform :ios, "9.0"
use_frameworks!

target 'QLSwift' do

    pod 'SwiftParsec', :git => 'https://github.com/tomvanduist/SwiftParsec.git'
    pod 'SnapKit', '~> 0.19'
    pod 'DTAlertView'

end

target 'QLSwiftTests' do
    
    pod 'SwiftParsec', :git => 'https://github.com/tomvanduist/SwiftParsec.git'

end

