package nl.uva.sea.ql.interpreter;

import java.util.*;
import java.util.function.BinaryOperator;
import nl.uva.sea.ql.answerTable.AnswerTable;
import nl.uva.sea.ql.ast.expr.*;
import nl.uva.sea.ql.ast.question.Question;
import nl.uva.sea.ql.generalPurposeVisitors.GeneralizedASTVisitor;

/**
 * Objects of this class keep track of conditions for each
 * <code>ConditionalStatement</code> and create <code>DisplayableQuestion</code>s
 * with these conditions for each <code>Question</code> they <code>visit</code>.
 * 
 * @author Olav Trauschke
 * @version 26-mar-2016
 */
public class DisplayableQuestionGenerator extends GeneralizedASTVisitor {
    
    private final AnswerTable answerTable;
    private final Stack<Expr> conditions;
    private final List<DisplayableQuestion> result;
    
    /**
     * Constructor for objects of this class.
     * 
     * @param theAnswerTable an <code>AnswerTable</code> mapping all
     *                      <code>Ident</code>s <code>Question</code>s or
     *                      <code>ConditionalStatement</code>s
     *                      <code>this DisplayableQuestionGenerator</code> may
     *                      visit may contain
     */
    public DisplayableQuestionGenerator(AnswerTable theAnswerTable) {
        answerTable = theAnswerTable;
        conditions = new Stack<>();
        result = new ArrayList<>();
    }
    
    /**
     * Create a <code>DisplayableQuestion</code> for a specified
     * <code>Question</code> with the conjuction of all available conditions as
     * condition.
     * 
     * @param question a <code>Question</code> to create a
     *                  <code>DisplayableQuestion</code> for
     */
    @Override
    public void visit(Question question) {
        Expr condition = createConjunctionOfConditions();
        DisplayableQuestion displayableQuestion
                = new DisplayableQuestion(condition, question, answerTable);
        result.add(displayableQuestion);
    }
    
    /**
     * Add a condition to <code>this DisplayableQuestionGenerator</code>.
     * 
     * @param condition an <code>Expr</code> representing the condition to add
     */
    public void addCondition(Expr condition) {
        conditions.push(condition);
    }
    
    /**
     * Remove the last condition that was added to it from
     * <code>this DisplayableQuestionGenerator</code>.
     */
    public void removeLastCondition() {
        conditions.pop();
    }
    
    /**
     * Returns <code>DisplayableQuestions</code> representing all
     * <code>Question</code>s <code>this DisplayableQuestionGenerator</code> has
     * <code>visit</code>ed.
     * 
     * @return a <code>List</code> of all <code>DisplayableQuestion</code>
     *          generated by <code>this DisplayableQuestionGenerator</code>
     */
    public List<DisplayableQuestion> getResult() {
        return result;
    }
    
    /**
     * @return an <code>Expr</code> representing the conjunction of all
     *          conditions that were add to (and not removed from)
     *          <code>this DisplayableQuestionGenerator</code>
     */
    private Expr createConjunctionOfConditions() {
        Expr top = new Bool(true);
        return conditions.stream().reduce(top, And::new);
    }
    
}
